Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -40,14 +40,15 @@ jobs:
 
       - name: Install dependencies
         run: |
-          brew install --formula cocoapods
-          cd ios && pod install
+          brew install cocoapods
+          if [ -d "ios" ]; then cd ios && pod install; else echo "iOS directory not found" && exit 1; fi
 
       - name: Build iOS App
         run: |
-          cd ios
+          if [ -d "ios" ]; then cd ios
           xcodebuild -workspace AudioRecorderApp.xcworkspace \
             -scheme AudioRecorderApp \
             -sdk iphoneos \
             -configuration Release \
-            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
+            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO; 
+          else echo "iOS directory not found" && exit 1; fi
